Update Action.yml

diff --git a/.github/workflows/Action.yml b/.github/workflows/Action.yml
--- a/.github/workflows/Action.yml
+++ b/.github/workflows/Action.yml
@@ -1,1 +1,80 @@
 
+name: Fetch new feeds and push content to Github Pages
+on:
+  push:
+    branches: ["main"]
+    paths:
+      - 'news.php'
+      - 'newsbase.html'
+  schedule:
+    - cron: '0 */2 * * *'  # Runs every 2 hrs
+  workflow_dispatch:
+
+permissions:
+  id-token: write
+  contents: write
+  actions: write
+  checks: write
+  deployments: write
+  discussions: write
+  issues: write
+  pages: write
+  packages: write
+  pull-requests: write
+  repository-projects: write
+  security-events: write
+  statuses: write
+
+concurrency:
+  group: "pages"
+  cancel-in-progress: false
+
+jobs:
+  deploy:
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-20.04
+    steps:
+  
+      - name: Checkout
+        uses: actions/checkout@v4  # Updated to v4
+      
+      - name: Setup Pages
+        uses: actions/configure-pages@v4  # Updated to v4
+      
+      - name: Run news.php
+        run: php news.php
+      
+      - name: Check for generated files
+        run: |
+          if [ ! -f news.html ]; then
+            echo "news.html not found!"
+            exit 1
+          fi
+          if [ ! -f newsfeed.json ]; then
+            echo "newsfeed.json not found!"
+            exit 1
+          fi
+      
+      - name: Commit files
+        run: |
+          git config user.name github-actions
+          git config user.email github-actions@github.com
+          git add --all
+          git commit -m "Updating the repository" || echo "No changes to commit"
+      
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          force: true
+      
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v3  # Updated to v3
+        with:
+          path: './public'  # Ensure your generated files are in this directory
+      
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v4  # Updated to v4
